### ISSUE TITLE
Sort sections on CRE page

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/OpenCRE#289]
Please sort each section on the CRE page, at least according to 'name' and if possible to 'name'+'section' because now NIST, ISO and ZAP entries are all mixed.

The key is in this code at CommonRequirementEnumeration.tsx

const linksByType = useMemo(() => (display ? orderLinksByType(groupLinksByType(display)) : {}), [display]);
  return (

**Comment by geekaryan** [comment]
Hello robvanderveer. I would like to work upon this issue. But I am having a trouble while cloning the repo I am getting this particular error.
error: invalid path 'cres/>>Authentication.yaml'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Can u help in figuring it out so I can contribute to the project.
Thank you

**Comment by robvanderveer** [comment]
Hey, it's great that you want to pick up this issue! I am copying Spyros as
he is more familiar with git than I am.
Best,
Rob

**Comment by northdpole** [comment]
Hey @geekaryan  thanks for offering to contribute!
I'm having trouble reproducing your issue, are you on windows or macos?

**Comment by geekaryan** [comment]
Thank you @northdpole  for helping me out. Now I can run it in my local environment but not able to push the code as the main branch is still behind and as you have mentioned by next week I will able to create a pull request. Till then I will be very happy if I am able to fix more issues,
