### ISSUE TITLE
Fix wrong title 'which is part of CREs' 

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/OpenCRE#336]
By design, 'which is part of CREs' is used on a CRE page to show what parent CRE the CRE has. This is correct. Example: https://www.opencre.org/cre/764-507
I noticed that the same title is used on a 'standard' page. That's wrong. That title should be 'Which is linked from CREs:' Example: https://www.opencre.org/node/standard/OWASP%20Cheat%20Sheets/section/Deserialization%20Cheat%20Sheet

**Comment by john681611** [comment]
Is this special text (which currently doesn't exist) only for Standard => CRE or is it for anything except CRE to CRE?

**Comment by robvanderveer** [comment]
John, I don't understand your question.

**Comment by john681611** [comment]
Sorry badly written. Is 'Which is linked from CREs:' only for when a CRE is below a standard or is it for other types that are not CRE->CRE?
