### ISSUE TITLE
Improve bottom text of Chat

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/OpenCRE#359]
Sidenote: there also is a PR to fix typos in the bottom text. I included those in the below
Let's start with the most important notices for users, then the sponsoring, and then things about risks.

I suggest: 
Answers are generated by Google's PALM2 Large Language Model, which uses the internet as training data, plus data from OpenCRE to be used as primary source (common requirements on how to implement cybersecurity). Note that even though this is the most reliable publicly available security chatbot, it is still generative AI which cannot be always 100% correct.

Model operations are generously funded by [Software Improvement Group](https://www.softwareimprovementgroup.com/).

Privacy & Security measures:
-Your question is sent to Heroku, the hosting provider for OpenCRE, and then to GCP, all via protected connections
-Your data isn't stored on OpenCRE servers.
-The OpenCRE team is committed to safeguarding your privacy and security. We've employed extensive measures to ensure this
-To review our code, visit: https://github.com/owasp/OpenCRE

The old bottom text is:
OpenCRE Chat uses Google's PALM2 LLM, you can find the code for OpenCRE in https://github.com/owaps/OpenCRE. Your question travels to Heroku (OpenCRE hosting provider) and then to GCP over a protected connection. Your data is never stored in the OpenCRE servers, you can start a new session by refreshing your page. The OpenCRE team has taken all reasonable precautions we could think off to protect your privacy and security.

**Comment by northdpole** [comment]
@robvanderveer is this fixed?
