### ISSUE TITLE
gap analysis: is connection strength correct?

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/OpenCRE#393]
NIST SSDF PW.4.4 links with strength 1 to SAMM defect tracking, but it goes from vulnerability management to dependency management and then from there to its parent supply chain management and there to PW.4.4.. Those are two steps. Not one

<- LINKED_TO <- Vulnerability management -> LINKED_TO -> NIST SSDF RV.1.1 Gather information from software acquirers, users, and public sources on potential vulnerabilities in the software and third-party components that the software uses, and investigate all credible reports. <- LINKED_TO <- Dependency management <- CONTAINS <- Supply chain management -> LINKED_TO -> NIST SSDF PW.4.4 Verify that acquired commercial, open-source, and all other third-party software components comply with the requirements, as defined by the organization, throughout their life cycles

**Comment by john681611** [comment]
This example should be corrected by avoiding going via standards in routing
