### ISSUE TITLE
gap analysisL seems to be missing links

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/OpenCRE#394]
<img width="1401" alt="image" src="https://github.com/OWASP/OpenCRE/assets/796794/e83a1274-e5b1-4d28-bbfb-9688ef375aba">
When analysing SAMM-NIST SSDF I notice that the first link RV.3.2. is strong, but when I hover over it, the link description shows a longer path, and that path contains RV.1.1 which would have strength zero, but it's not mentioned in the list. I'm confused.

<- LINKED_TO <- Dependency management -> LINKED_TO -> NIST SSDF RV.1.1 Gather information from software acquirers, users, and public sources on potential vulnerabilities in the software and third-party components that the software uses, and investigate all credible reports. <- LINKED_TO <- Vulnerability management -> LINKED_TO -> NIST SSDF RV.3.2 Analyze the root causes over time to identify patterns, such as a particular secure coding practice not being followed consistently.

**Comment by john681611** [comment]
We should not be linting via other standard records IMO. I've removed this in a fix PR.
