### ISSUE TITLE
Gapanalysis: punish 'Related' much less

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/OpenCRE#405]
Related is now +20 penalty. That's much too strong. Make it +2

**Comment by john681611** [comment]
2 is the cost of a single jump up the CRE chain considering that  "Related" Can be loose it should be a high penalty (Remember if we can find a non-related route that scores lower that is preferred)

**Comment by robvanderveer** [comment]
I should have put that more kindly. Please do, and I'll experiment with it to check how loose related can be.

**Comment by john681611** [comment]
I assume you mean this CRE: 
Architecture
CRE: 155-155

**Comment by john681611** [comment]
<img width="285" alt="Screenshot 2023-10-05 at 10 19 41" src="https://github.com/OWASP/OpenCRE/assets/10814889/be69e8c9-96bf-4be9-920c-c6eba5d3f504">
Ok found an example of it being connected. Suspect its caused by this https://github.com/OWASP/OpenCRE/issues/405 basically its being out competed
