### ISSUE TITLE
Gapanalysis: seems to be a bug in the gap analysis algorithm

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/OpenCRE#406]
When I map the top 10 to CWE. I see a list of CWE's with 'Insecure design' but they all link to secure data storage, while insecure design is also linked to 'Architecture'. It seems to miss that.
https://tmp-cre-d004be88f13c.herokuapp.com/gap_analysis?base=OWASP%20Top%2010%202021&compare=CWE
https://tmp-cre-d004be88f13c.herokuapp.com/node/standard/OWASP%20Top%2010%202021/section/Insecure%20Design

Once this is fixed I can test further.

**Comment by john681611** [comment]
I'm confused about the issue here. What is the intended outcome?

**Comment by robvanderveer** [comment]
The expected outcome is that there should be CWEs that are connected to 'Architecture' and there are none.

**Comment by john681611** [comment]
<img width="285" alt="Screenshot 2023-10-05 at 10 19 41" src="https://github.com/OWASP/OpenCRE/assets/10814889/be69e8c9-96bf-4be9-920c-c6eba5d3f504">

Ok found an example of it being connected. Suspect its caused by this #405 basically its being out-competed

**Comment by robvanderveer** [comment]
You are right. I didn't expect them in 'Weak' but they were there.
