### ISSUE TITLE
Mapanalysis: something weird with Cheat sheets

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/OpenCRE#424]
If I pick the op 10 or ASVS on the left side and Cheat sheets on the right side, it will only show me the secrets management cheat sheet.

**Comment by john681611** [comment]
Can I have some images to understand what is going on here? Unless there is a bug in the logic its most likely the data setup being not ideal

**Comment by robvanderveer** [comment]
<img width="1269" alt="image" src="https://github.com/OWASP/OpenCRE/assets/796794/c44e1859-fa6d-4adf-a75a-7f21b954c9cb">
which is incomplete. For example A03 injection is linked to injection projection https://staging.opencre.org/cre/760-764 which is related to 'encode user input before logging' - as shown on that cre page, which is linked to the cheat sheet 'Standard : OWASP Cheat Sheets : Logging Cheat Sheet' but the latter doesn't show up in the screenshot.

**Comment by john681611** [comment]
Ok I'll checkout out the data graph and see If I can understand the reason why

**Comment by northdpole** [comment]
That's my bad, will fix this myself
