### ISSUE TITLE
Mapanalyis: ignore 'Cross cutting concerns' as a node

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/OpenCRE#425]
We should not link to other times through being contained in 'Cross cutting concern's because there is no conceptual relation between the topics under cross cutting concerns.

**Comment by john681611** [comment]
This is a wider data issue and the need to add in more relation types to add looser relations. Not sure I'm suitable for this issue with my current knowlage.

**Comment by robvanderveer** [comment]
John, as far as I can see we will not need more nodes like 'cross-cutting concerns' in the near future. For now it is sufficient to implement an explicit exception by never traveling through this node. 
Apart from that, we can implement node-dependent penalties in a later stage.
