### ISSUE TITLE
Using Google account with the chat bot required several attempts to authenticate

### ISSUE THREAD

**Issue by NathanDotTo** [OWASP/OpenCRE#485]
### **What is the issue?**

I followed the link to the https://www.opencre.org/chatbot this morning. It took several attempts to use my Google account. 

### Expected Behaviour

I should have selected my Google account just once, and that should have taken me back to the chat bot page.

### Actual Behaviour

I selected my Google account, was taken to the chat bot page, then redirected back to selecting my Google account again, and so on for several cycles. It eventually worked.

### Steps to reproduce

I am using Safari on the latest version of MacOS. Let's see if anyone else has this issue.

**Comment by northdpole** [comment]
thanks @NathanDotTo , we fixed this now, was an uncaught exception
