### ISSUE TITLE
Function tabs on the home page

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/OpenCRE#502]
Home page: 
-Make it just like every page. So not title. Just tabs at the top: OpenCRE, OpenCRE-chat, Map analyis and then the search bar on the right
-Add a tab ‘Browse’ that takes you to https://www.opencre.org/root_cres which we can later replace with the explorer I think

**Comment by dlicheva** [comment]
Changes:
- New header style, including blue background
- Search bar in header on all pages
- New logo (might be changed again soon)
