### ISSUE TITLE
Make standard tags in explorer link directly to the right entry/entries for the CRE

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/OpenCRE#507]
The Explorer now shows buttons for the standards in rows. Currently that button takes you to the entire standard. Instead, please let it link to the deeplink (if available) to the content of that standard, for the CRE in that row. 
Sometimes these are multiple standards (like often with Capec): that could take the user to an OpenCRE page that shows the CRE and just filters on CAPEC. So then the user can choose which capec link to go to.

Am I correct in assigning this to you Diana? :)

**Comment by dlicheva** [comment]
Thanks @robvanderveer , this should be done here: https://github.com/OWASP/OpenCRE/pull/513
Could you have a look to see if that's the right idea please?
