### ISSUE TITLE
Remove 'browse topics' button on Home?

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/OpenCRE#511]
Dear Diana, thank you for the great new look!
Could you remove the browse topics button on the home page. It takes up much vertical space and we already have the browse menu and we mention browse with a hyperlink in the 'examples of use' list.
If you do, could you minimize the vertical space of that part of the screen - of course while keeping it looking nice. Thanks!
On a sidenote: I noticed a horizontal white bar appearing on the homepage on my iphone 14 in safari. Only on the home page. Between the top dark blue row and the second blue row.
Cheers.

**Comment by dlicheva** [comment]
Thank you @robvanderveer!
I think the Browse button on the homepage gives the user a clear indication of where to start. 
I'm happy to make it smaller and reduce the space around it, so users can see the entire page without much scrolling.
I'll test it on mobile as well and cleanup issues there too, thanks for letting me know :+1:

**Comment by robvanderveer** [comment]
I like your thinking and agree. A bit less vertical space would be nice indeed to reduce the scrolling. Later we can let the browse topics link to the new explorer which is a more powerful feature. Thanks!

**Comment by dlicheva** [comment]
Hi @robvanderveer , I've updated the styles here: https://github.com/OWASP/OpenCRE/pull/512
Let me know if that looks ok please :) 
Thanks!
