### ISSUE TITLE
Explorer build up is slow and no wait animation

### ISSUE THREAD

**Issue by robvanderveer** [OWASP/OpenCRE#515]
The first build up of explorer takes a couple of seconds and shows no waiting animation (it appears but quite late).
Optimization is in order I guess, or showing that animation straight away. 
I thought the page was broken first.
Chrome on a Mac.

**Comment by dlicheva** [comment]
Thanks @robvanderveer ! The loading indicator is fixed [here](https://github.com/OWASP/OpenCRE/pull/536).
