### ISSUE TITLE
python cre.py --upstream_sync - ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by 5t00g1t** [OWASP/OpenCRE#551]
### **What is the issue?**

After **make install** should there be an instruction to run **pip install -r requirements.txt** ?

### Expected Behaviour

What should have happened?

Requirements should be installed and the command **python cre.py --upstream_sync** should not produce an error.

### Actual Behaviour

What actually happened?

When running 

Getting: **ModuleNotFoundError: No module named 'click'**

How can we reproduce the error?

Set up a new project and follow steps as outlined in README

**Comment by northdpole** [comment]
you need to activate the virtual environment first with `source venv/bin/activate`
