### ISSUE TITLE
ZAP is now Checkmarx

### ISSUE THREAD

**Issue by sydseter** [OWASP/OpenCRE#556]
### **What is the issue?**

ZAP is now owned by Checkmarx and is in their portfolio, and we should not be seen to endorse one company's products and not another company's products. 

In addition some ZAP features will now become paid-for, which is not truly open source

Should we be concerned about the use of ZAP rules here?

**Comment by sydseter** [comment]
see: https://github.com/OWASP/www-project-developer-guide/issues/282

**Comment by thc202** [comment]
Yes see https://github.com/OWASP/www-project-developer-guide/issues/282#issuecomment-2378776589 and https://github.com/OWASP/www-project-developer-guide/issues/282#issuecomment-2378782767

**Comment by sydseter** [comment]
It may have been to rushed from myside.
