### ISSUE TITLE
Contributing guidance is wrong or out-of-date

### ISSUE THREAD

**Issue by kingthorin** [OWASP/OpenCRE#560]
### **What is the issue?**

https://github.com/OWASP/OpenCRE/blob/main/CONTRIBUTING.md#adding-cres-and-mappings
 
 Lists `/cres` and yaml files which no longer seem to exist.

### Expected Behaviour

Valid instructions.

### Actual Behaviour

Invalid instructions 🤪

### Steps to reproduce

Visit the provided link.

**Comment by robvanderveer** [comment]
Has been fixed in the recent documentation update

**Comment by kingthorin** [comment]
Thanks!
